server:
    port: 8080
    max-http-header-size: 65536

# Disable favicon
spring:
    mvc:
        favicon:
            enabled: false

management:
        endpoints:
                web:
                        exposure:
                                include: health,info,prometheus

# mappings filepath
#mappings:
#    file:
#        path: classpath:mappings.json
#        path: file:/etc/sth/
statstool:
    supported-diagrams:
    charts:
        -
            name: "column"
            diagram-id: 0
            description: "Column Diagram"
            image-url: "images/imagePlaceholder.svg"
            is-polar: false
            supported-libraries:
                - "HighCharts"
                - "GoogleCharts"
                - "eCharts"
    polars:
    maps:
    specials:
    miscs: