spring:
  datasources:
    - id: monitor.public
      url: jdbc:postgresql://esperos.di.uoa.gr:5432/monitor
      driver-class-name: org.postgresql.Driver
      username: dnet
      password: dnetPwd
    - id: cache
      username: sa
      password:
      url: jdbc:hsqldb:file:/tmp/cache
      driver-class-name: org.hsqldb.jdbcDriver
  redis:
    host: vereniki.athenarc.gr
    port: 6379
    password: redisPassword
  # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database: postgresql
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 55

  # custom configuration
statstool:
  result_limit: 70
  cache:
    enabled: false
    storage: redis
    update:
      entries: 5000
      time: 10800
  namedqueries:
    path: ...
  mappings:
    file:
      path: classpath:mappings.json
